spring:
  application:
    name: e-commerce
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_NAME:e-commerce}
    username: root
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 15MB
  flyway:
    enabled: true
    validate-on-migrate: true
    target: ${FLYWAY_TARGET:latest}