name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      SPRING_PROFILES_ACTIVE: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run the tests
      run: mvn -B verify org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:check

    - name: Upload Jacoco Report
      uses: 'actions/upload-artifact@v4'
      with:
        name: jacoco-report
        path: ${{ github.workspace }}/target/site/jacoco/index.html